git:
  depth: 10
sudo: false
language: node_js
node_js:
  - '7'
  - '6'
before_install: npm i -g npm@"$(jq -r '.engines.npm' package.json)"

script: lerna bootstrap && npm run test
after_success: npm run report-coverage
