git:
  depth: 10
sudo: false
language: node_js
node_js:
  - '8'
  - '6.9.0'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - yarn
  - yarn run lerna bootstrap
script:
  - yarn run lerna run build
  - yarn run test
after_success: yarn run report-coverage
